#!/bin/bash

TOOLC_HOME=~/.toolc
ARCH=$(uname -m)
OS=$(uname)

directory=$(echo "$OS-$ARCH" | tr '[:upper:]' '[:lower:]')

which git 1>/dev/null
if [ -z "$?" ]; then
    echo "you must install git at first."
    exit 1
fi

function _do_install()
{
    if [ ! -d "$TOOLC_HOME" ]; then
        mkdir -p $TOOLC_HOME
        git clone https://github.com/ISSKJ/toolc-dist.git  $TOOLC_HOME/toolc-dist -n --depth 1
    fi
    PWD=$(pwd)
    cd $TOOLC_HOME/toolc-dist
    git checkout HEAD $directory
    cd $PWD
    echo "toolc installed. Please add the line to PATH"
    echo "export PATH=\$PATH:$TOOLC_HOME/toolc-dist/$directory"
}

function _do_uninstall()
{
    rm -rf $TOOLC_HOME;
    rm -rf toolc-dist;
    echo "toolc uninstalled."
}

function _do_update()
{
    PWD=$(pwd)
    cd $TOOLC_HOME/toolc-dist
    git pull
    cd $PWD
    echo "toolc updated."
}

function _do_reinstall()
{
    _do_uninstall
    _do_install
}

function _do_usage()
{
    echo "$0 [ install | uninstall | reinstall | update ]"
}


case "$1" in
    "install")
        _do_install
        ;;
    "uninstall")
        _do_uninstall
        ;;
    "reinstall")
        _do_reinstall
        ;;
    "update")
        _do_update
        ;;
    *)
        _do_usage
        ;;
esac
